import { makeStyles } from "@material-ui/core/styles"

const useStyles = makeStyles((theme) => ({
  box: {
    width: "100%",
  },
  root: {
    background: "rgb(41,41,41)",
    height: "100%",
    paddingBottom: "0vh",
  },
  background1: {
    position: "relative",
    backgroundSize: "cover",
    backgroundAttachment: "fixed",
    [theme.breakpoints.up("xl")]: {
      top: "0rem",
      height: "62vh",
      width: "100vw",
    },
    [theme.breakpoints.only("lg")]: {
      top: "0rem",
      height: "100vh",
      width: "100vw",
    },
    [theme.breakpoints.only("md")]: {
      top: "0rem",
      height: "100vh",
      width: "100vw",
    },
    [theme.breakpoints.only("sm")]: {
      top: "0rem",
      height: "100vh",
      width: "100vw",
    },
    [theme.breakpoints.down("xs")]: {
      top: "0rem",
      height: "100vh",
      width: "100vw",
    },
  },
  orangeBox: {
    position: "absolute",
    backgroundColor: "rgba(120,20,4,0.6)",
    [theme.breakpoints.down("xs")]: {
      right: 0,
      top: "17rem",
      height: "8rem",
      width: "102vw",
    },
    [theme.breakpoints.only("sm")]: {
      right: 0,
      top: "9rem",
      height: "15rem",
      width: "56vw",
    },
    [theme.breakpoints.only("md")]: {
      right: 0,
      top: "10rem",
      height: "15rem",
      width: "54vw",
    },
    [theme.breakpoints.only("lg")]: {
      right: 0,
      top: "15rem",
      height: "17rem",
      width: "51vw",
    },
    [theme.breakpoints.up("xl")]: {
      right: 0,
      top: "15rem",
      height: "15rem",
      width: "50vw",
    },
  },
  section1: {
    position: "absolute",
    zIndex: 1,
    [theme.breakpoints.down("xs")]: {
      top: "23%",
      marginInline: "12%",
      width: "79vw",
    },
    [theme.breakpoints.only("sm")]: {
      top: "32%",
      marginInline: "15%",
      width: "72vw",
    },
    [theme.breakpoints.only("md")]: {
      top: "33%",
      marginInline: "23%",
      width: "72vw",
    },
    [theme.breakpoints.only("lg")]: {
      top: "48%",
      marginInline: "31%",
      width: "72vw",
    },
    [theme.breakpoints.up("xl")]: {
      top: "40%",
      marginInline: "40%",
      width: "100%",
    },
  },
  title1: {
    color: "white",
    fontFamily: ["Poppins", "sans-serif"],
    [theme.breakpoints.up("xl")]: {
      fontSize: "68px",
      fontWeight: "700",
      lineHeight: "4rem",
      letterSpacing: "0.08rem",
      width: "60%",
    },
    [theme.breakpoints.only("lg")]: {
      fontSize: "68px",
      fontWeight: "700",
      lineHeight: "4.5rem",
      letterSpacing: "0.1rem",
      width: "87%",
    },
    [theme.breakpoints.only("md")]: {
      fontSize: "68px",
      fontWeight: "700",
      lineHeight: "4.5rem",
      letterSpacing: "0.1rem",
      width: "100%",
    },
    [theme.breakpoints.down("sm")]: {
      fontSize: "68px",
      fontWeight: "700",
      lineHeight: "3rem",
      letterSpacing: "0.1rem",
      width: "100%",
    },
    [theme.breakpoints.down("xs")]: {
      fontSize: "38px",
      fontWeight: "700",
      lineHeight: "2.5rem",
      letterSpacing: "0.1rem",
      width: "100%",
      textAlign: "center"
    },
  },
  content1: {
    color: "white",
    fontFamily: ["Montserrat", "sans-serif"],
    [theme.breakpoints.up("xl")]: {
      marginTop: "1.3rem",
      fontSize: "20px",
      marginLeft: "7rem",
    },
    [theme.breakpoints.only("lg")]: {
      marginTop: "1rem",
      fontSize: "20px",
      marginLeft: "7rem",
    },
    [theme.breakpoints.only("md")]: {
      marginTop: "1rem",
      fontSize: "20px",
      marginLeft: "7rem",
    },
    [theme.breakpoints.only("sm")]: {
      marginTop: "1rem",
      fontSize: "20px",
      marginLeft: "7rem",
    },
    [theme.breakpoints.down("xs")]: {
      marginTop: "1rem",
      fontSize: "16px",
      textAlign: "center"
    },
  },
  section2: {
    [theme.breakpoints.up("xl")]: {
      marginTop: "5vh",
      marginInline: "19%",
    },
    [theme.breakpoints.only("lg")]: {
      marginTop: "5vh",
      marginInline: "10%",
    },
    [theme.breakpoints.only("md")]: {
      marginTop: "5vh",
      marginInline: "5%",
    },
    [theme.breakpoints.only("sm")]: {
      marginTop: "7vh",
      marginInline: "5%",
    },
    [theme.breakpoints.down("xs")]: {
      marginTop: "10vh",
      marginInline: "5%",
    },
  },
  cardDetail: {
    [theme.breakpoints.up("xl")]: {
      marginTop: "2rem",
      marginInline: "15%",
    },
    [theme.breakpoints.only("lg")]: {
      marginTop: "5vh",
      // marginInline: "17%",
    },
    [theme.breakpoints.only("md")]: {
      marginTop: "5vh",
      // marginInline: "15%",
    },
    [theme.breakpoints.only("sm")]: {
      marginTop: "5vh",
      // marginInline: "15%",
    },
    [theme.breakpoints.down("xs")]: {
      marginTop: "5vh",
      // marginInline: "10%",
    },
  },
  title2: {
    color: "white",
    fontFamily: ["Poppins", "sans-serif"],
    [theme.breakpoints.up("xl")]: {
      marginTop: "1.3rem",
      fontSize: "45px",
      fontWeight: "800",
      width: "94%",
      textAlign: "left",
    },
    [theme.breakpoints.only("lg")]: {
      marginTop: "1rem",
      fontSize: "45px",
      fontWeight: "800",
      textAlign: "left",
      width: "100%",
    },
    [theme.breakpoints.only("md")]: {
      marginTop: "1rem",
      fontSize: "45px",
      fontWeight: "800",
      textAlign: "center",
      width: "100%",
      // marginLeft: "5rem"
    },
    [theme.breakpoints.only("sm")]: {
      marginTop: "1rem",
      fontSize: "45px",
      textAlign: "left",
      fontWeight: "800",
      width: "95%",
      textAlign: "center",
    },
    [theme.breakpoints.down("xs")]: {
      marginTop: "1rem",
      fontSize: "32px",
      fontWeight: "700",
      textAlign: "left",
      width: "100%",
      lineHeight: "2rem",
      textAlign: "center",
    },
  },
  subtitle2: {
    color: "white",
    textAlign: "left",
    fontFamily: ["Montserrat", "sans-serif"],
    [theme.breakpoints.up("xl")]: {
      marginTop: "1.3rem",
      fontSize: "20.8px",
      fontWeight: "800",
      width: "94%",
      marginBottom: "2rem",
    },
    [theme.breakpoints.only("lg")]: {
      // marginTop: "1rem",
      fontSize: "16px",
      fontWeight: "800",
      width: "100%",
      marginBottom: "1rem",
    },
    [theme.breakpoints.only("md")]: {
      // marginTop: "1rem",
      fontSize: "16px",
      fontWeight: "800",
      width: "100%",
      marginBottom: "1rem",
    },
    [theme.breakpoints.only("sm")]: {
      // marginTop: "1rem",
      fontSize: "16px",
      fontWeight: "800",
      width: "95%",
      marginBottom: "1rem",
    },
    [theme.breakpoints.down("xs")]: {
      // marginTop: "1rem",
      fontSize: "16px",
      fontWeight: "700",
      width: "100%",
      marginBottom: "1rem",
      lineHeight: "2rem",
    },
  },
  content2: {
    color: "white",
    whiteSpace: "pre-line",
    fontFamily: ["Montserrat", "sans-serif"],
    [theme.breakpoints.up("xl")]: {
      fontSize: "20.8px",
      fontWeight: "400",
      width: "100%",
    },
    [theme.breakpoints.only("lg")]: {
      fontSize: "16px",
      fontWeight: "400",
      width: "97%",
    },
    [theme.breakpoints.only("md")]: {
      fontSize: "16px",
      fontWeight: "400",
      width: "95%",
    },
    [theme.breakpoints.only("sm")]: {
      fontSize: "16px",
      fontWeight: "400",
      width: "100%",
    },
    [theme.breakpoints.down("xs")]: {
      fontSize: "16px",
      fontWeight: "400",
      width: "100%",
    },
  },
  section3: {
    [theme.breakpoints.up("xl")]: {
      marginTop: "5vh",
      marginBottom: "-0.8vh",
      marginInline: "12.5%",
    },
    [theme.breakpoints.only("lg")]: {
      marginTop: "10vh",
      marginBottom: "-1rem",
      // height: "40vh"
      // marginInline: "17%",
    },
    [theme.breakpoints.only("md")]: {
      marginTop: "9vh",
      marginBottom: "-1rem",
      // marginInline: "15%",
    },
    [theme.breakpoints.only("sm")]: {
      marginTop: "10vh",
      marginBottom: "-1rem",
      // marginInline: "15%",
    },
    [theme.breakpoints.down("xs")]: {
      marginTop: "10vh",
      marginBottom: "-1rem",
      // marginInline: "10%",
    },
  },
  orangeBox3: {
    position: "relative",
    bottom: "0",
    background: "rgb(121,17,0)",
    [theme.breakpoints.up("xl")]: {
      height: "20rem",
      width: "100%",
      padding: "5rem 10rem",
    },
    [theme.breakpoints.only("lg")]: {
      height: "20rem",
      width: "100%",
      padding: "5rem 10rem",
    },
    [theme.breakpoints.only("md")]: {
      height: "18rem",
      width: "100%",
      padding: "4rem 10rem",
    },
    [theme.breakpoints.only("sm")]: {
      height: "20rem",
      width: "100%",
      padding: "5rem 7rem",
    },
    [theme.breakpoints.down("xs")]: {
      height: "100%",
      width: "100%",
      padding: "2rem 2rem",
    },
  },
  content3: {
    color: "white",
    whiteSpace: "pre-line",
    fontFamily: ["Montserrat", "sans-serif"],
    [theme.breakpoints.up("xl")]: {
      fontSize: "18px",
      fontWeight: "400",
      width: "100%",
    },
    [theme.breakpoints.only("lg")]: {
      fontSize: "18px",
      fontWeight: "400",
      width: "100%",
    },
    [theme.breakpoints.only("md")]: {
      fontSize: "18px",
      fontWeight: "400",
      width: "100%",
    },
    [theme.breakpoints.only("sm")]: {
      fontSize: "18px",
      fontWeight: "400",
      width: "100%",
    },
    [theme.breakpoints.down("xs")]: {
      fontSize: "18px",
      fontWeight: "400",
      width: "100%",
    },
  },
  title3: {
    color: "white",
    textAlign: "left",
    fontFamily: ["Montserrat", "sans-serif"],
    [theme.breakpoints.up("xl")]: {
      // marginTop: "1.3rem",
      fontSize: "24px",
      fontWeight: "600",
      width: "94%",
      marginBottom: "0.5rem",
    },
    [theme.breakpoints.only("lg")]: {
      // marginTop: "1rem",
      fontSize: "24px",
      fontWeight: "700",
      width: "100%",
      marginBottom: "0.5rem",
      letterSpacing: "0rem",
    },
    [theme.breakpoints.only("md")]: {
      // marginTop: "1rem",
      fontSize: "24px",
      fontWeight: "700",
      width: "100%",
      marginBottom: "0.5rem",
    },
    [theme.breakpoints.only("sm")]: {
      textAlign: "left",
      // marginTop: "1rem",
      fontSize: "24px",
      fontWeight: "700",
      width: "100%",
      marginBottom: "0.5rem",
      lineHeight: "3rem",
    },
    [theme.breakpoints.down("xs")]: {
      // marginTop: "1rem",
      fontSize: "24px",
      fontWeight: "700",
      width: "100%",
      marginBottom: "0.5rem",
    },
  },
  assessmentBtn: {
    textTransform: "none",
    backgroundColor: "rgb(0,0,0)",
    borderRadius: "0px",
    color: "white",
    [theme.breakpoints.up("xl")]: {
      marginTop: "2rem",
      maxHeight: "3vh",
      minHeight: "3vh",
      maxWidth: "5vw",
      minWidth: "5vw",
      fontSize: "14px",
    },
    [theme.breakpoints.only("lg")]: {
      marginTop: "2rem",
      maxHeight: "5vh",
      minHeight: "5vh",
      maxWidth: "8vw",
      minWidth: "8vw",
      fontSize: "12px",
    },
    [theme.breakpoints.only("md")]: {
      marginTop: "2rem",
      maxHeight: "5vh",
      minHeight: "5vh",
      maxWidth: "10vw",
      minWidth: "10vw",
      fontSize: "12px",
    },
    [theme.breakpoints.only("sm")]: {
      marginTop: "2rem",
      maxHeight: "5vh",
      minHeight: "5vh",
      maxWidth: "14vw",
      minWidth: "14vw",
      fontSize: "12px",
    },
    [theme.breakpoints.down("xs")]: {
      marginTop: "2rem",
      maxHeight: "5vh",
      minHeight: "5vh",
      maxWidth: "30vw",
      minWidth: "30vw",
      fontSize: "12px",
    },
  },
  section4: {
    [theme.breakpoints.up("xl")]: {
      padding: "2% 13%",
      height: "55vh",
    },
    [theme.breakpoints.only("lg")]: {
      padding: "5% 13%",
      height: "100vh",
    },
    [theme.breakpoints.only("md")]: {
      padding: "9% 15%",
      height: "95vh",
    },
    [theme.breakpoints.only("sm")]: {
      padding: "8% 13%",
      height: "90vh",
    },
    [theme.breakpoints.down("xs")]: {
      padding: "10% 10%",
      height: "95vh",
    },
  },
  title4: {
    color: "white",
    textAlign: "left",
    fontFamily: ["Poppins", "sans-serif"],
    [theme.breakpoints.up("xl")]: {
      // marginTop: "1.3rem",
      fontSize: "26px",
      fontWeight: "600",
      width: "94%",
      marginBottom: "0.5rem",
    },
    [theme.breakpoints.only("lg")]: {
      // marginTop: "1rem",
      fontSize: "26px",
      fontWeight: "700",
      width: "100%",
      marginBottom: "-2rem",
      letterSpacing: "0rem",
    },
    [theme.breakpoints.only("md")]: {
      // marginTop: "1rem",
      fontSize: "26px",
      fontWeight: "700",
      width: "100%",
      // marginBottom: "0.5rem",
    },
    [theme.breakpoints.only("sm")]: {
      textAlign: "left",
      // marginTop: "1rem",
      fontSize: "26px",
      fontWeight: "700",
      width: "50%",
      // marginBottom: "0.5rem",
      lineHeight: "3rem",
    },
    [theme.breakpoints.down("xs")]: {
      // marginTop: "1rem",
      fontSize: "26px",
      fontWeight: "700",
      width: "100%",
      // marginBottom: "0.5rem",
    },
  },
  content4: {
    color: "white",
    whiteSpace: "pre-line",
    fontFamily: ["Montserrat", "sans-serif"],
    [theme.breakpoints.up("xl")]: {
      fontSize: "18px",
      fontWeight: "400",
      width: "100%",
    },
    [theme.breakpoints.only("lg")]: {
      fontSize: "16px",
      fontWeight: "400",
      width: "100%",
    },
    [theme.breakpoints.only("md")]: {
      fontSize: "16px",
      fontWeight: "400",
      width: "100%",
    },
    [theme.breakpoints.only("sm")]: {
      fontSize: "16px",
      fontWeight: "400",
      width: "100%",
    },
    [theme.breakpoints.down("xs")]: {
      fontSize: "16px",
      fontWeight: "400",
      width: "100%",
    },
  },
  submitBtn: {
    textTransform: "none",
    backgroundColor: "rgb(121,17,0)",
    borderRadius: "10px",
    color: "white",
    [theme.breakpoints.up("xl")]: {
      maxHeight: "3vh",
      minHeight: "3vh",
      maxWidth: "5vw",
      minWidth: "5vw",
      fontSize: "14px",
    },
    [theme.breakpoints.only("lg")]: {
      maxHeight: "6vh",
      minHeight: "6vh",
      maxWidth: "14vw",
      minWidth: "14vw",
      fontSize: "15px",
    },
    [theme.breakpoints.only("md")]: {
      maxHeight: "5vh",
      minHeight: "5vh",
      maxWidth: "10vw",
      minWidth: "10vw",
      fontSize: "15px",
    },
    [theme.breakpoints.only("sm")]: {
      maxHeight: "5vh",
      minHeight: "5vh",
      maxWidth: "14vw",
      minWidth: "14vw",
      fontSize: "15px",
    },
    [theme.breakpoints.down("xs")]: {
      maxHeight: "6vh",
      minHeight: "6vh",
      maxWidth: "100%",
      minWidth: "100%",
      fontSize: "15px",
    },
  },
}))
export default useStyles
